name: Release

on:
  push:
    branches:
    - release
    tags:
    - "v*"

jobs:
  release-latexmk:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
        name: checkout code
      - uses: xu-cheng/texlive-action/full@v1
        name: build with latexmk
        with:
          run: |
            latexmk main.tex -halt-on-error -time -xelatex
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref }}
          body: "New release ${{ github.ref }}"
          draft: true
          prerelease: false
          files: |
            main.pdf